# Generated by Django 5.2.17 on 2026-09-23 04:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("cambio", "0001_initial"),
        ("core", "0003_remove_institucion_codigo_dea"),
        ("gastos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código SUDEBAN, ej. 0102.", max_length=4, unique=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "banco",
                "verbose_name_plural": "bancos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "moneda_fija",
                    models.CharField(
                        blank=True,
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")],
                        help_text="Vacío = admite Bs. o USD. Ej: 'Divisa efectivo' y 'Zelle' solo admiten USD.",
                        max_length=3,
                        null=True,
                    ),
                ),
                ("requiere_banco_destino", models.BooleanField(default=False)),
                ("requiere_banco_origen", models.BooleanField(default=False)),
                ("requiere_referencia", models.BooleanField(default=False)),
                ("requiere_telefono", models.BooleanField(default=False)),
                ("requiere_cedula", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "forma de pago",
                "verbose_name_plural": "formas de pago",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConceptoIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[("unico", "Único"), ("mensual", "Mensual")],
                        default="unico",
                        max_length=10,
                    ),
                ),
                (
                    "monto_sugerido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valor por defecto cuando no hay un monto específico para el grado/período en «Montos por concepto».",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "moneda_sugerida",
                    models.CharField(
                        blank=True,
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fondo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fondo al que entra el dinero. Vacío = Fondo General.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conceptos_ingreso",
                        to="gastos.fondo",
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto de ingreso",
                "verbose_name_plural": "conceptos de ingreso",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAporte",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "uuid_cliente",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Idempotencia de la cola offline (Fase 7). Vacío en los aportes hechos en línea.",
                        null=True,
                    ),
                ),
                (
                    "mes_cubierto",
                    models.DateField(
                        blank=True,
                        help_text="Día 1 del mes que cubre este aporte. Obligatorio si el concepto es mensual.",
                        null=True,
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("referencia", models.CharField(blank=True, max_length=40)),
                ("telefono_emisor", models.CharField(blank=True, max_length=11)),
                ("cedula_titular", models.CharField(blank=True, max_length=20)),
                ("nombre_titular", models.CharField(blank=True, max_length=150)),
                ("nota_pago", models.TextField(blank=True)),
                (
                    "entregado_por_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Si quien entrega no es un representante registrado.",
                        max_length=150,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("registrado", "Registrado"),
                            ("observado", "Observado"),
                            ("verificado", "Verificado"),
                            ("anulado", "Anulado"),
                        ],
                        default="registrado",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
                ("fecha_verificacion", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("desviacion_confirmada", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "banco_destino",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ingresos.banco",
                    ),
                ),
                (
                    "banco_origen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ingresos.banco",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ingresos.conceptoingreso",
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="academico.representante",
                    ),
                ),
                (
                    "fondo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Copiado de concepto.fondo al registrar (o el Fondo General si el concepto no tiene uno).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "forma_pago",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ingresos.formapago",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Vacío para ingresos sin estudiante (rifas, donaciones — D-19).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="academico.inscripcion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Denormalizado: de inscripcion.periodo si hay inscripción, o el período activo al registrar.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.periodoescolar",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cambio.tasacambio",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aporte",
                "verbose_name_plural": "historical aportes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Aporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "uuid_cliente",
                    models.UUIDField(
                        blank=True,
                        help_text="Idempotencia de la cola offline (Fase 7). Vacío en los aportes hechos en línea.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "mes_cubierto",
                    models.DateField(
                        blank=True,
                        help_text="Día 1 del mes que cubre este aporte. Obligatorio si el concepto es mensual.",
                        null=True,
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("referencia", models.CharField(blank=True, max_length=40)),
                ("telefono_emisor", models.CharField(blank=True, max_length=11)),
                ("cedula_titular", models.CharField(blank=True, max_length=20)),
                ("nombre_titular", models.CharField(blank=True, max_length=150)),
                ("nota_pago", models.TextField(blank=True)),
                (
                    "entregado_por_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Si quien entrega no es un representante registrado.",
                        max_length=150,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("registrado", "Registrado"),
                            ("observado", "Observado"),
                            ("verificado", "Verificado"),
                            ("anulado", "Anulado"),
                        ],
                        default="registrado",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
                ("fecha_verificacion", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("desviacion_confirmada", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aportes_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes_entregados",
                        to="academico.representante",
                    ),
                ),
                (
                    "fondo",
                    models.ForeignKey(
                        help_text="Copiado de concepto.fondo al registrar (o el Fondo General si el concepto no tiene uno).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío para ingresos sin estudiante (rifas, donaciones — D-19).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes",
                        to="academico.inscripcion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        help_text="Denormalizado: de inscripcion.periodo si hay inscripción, o el período activo al registrar.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes",
                        to="core.periodoescolar",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes",
                        to="cambio.tasacambio",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aportes_verificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "banco_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes_como_destino",
                        to="ingresos.banco",
                    ),
                ),
                (
                    "banco_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes_como_origen",
                        to="ingresos.banco",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes",
                        to="ingresos.conceptoingreso",
                    ),
                ),
                (
                    "forma_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aportes",
                        to="ingresos.formapago",
                    ),
                ),
            ],
            options={
                "verbose_name": "aporte",
                "verbose_name_plural": "aportes",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["periodo", "estado"],
                        name="ingresos_ap_periodo_e99e03_idx",
                    ),
                    models.Index(
                        fields=["inscripcion", "fecha_pago"],
                        name="ingresos_ap_inscrip_23790a_idx",
                    ),
                    models.Index(
                        fields=["registrado_por", "estado"],
                        name="ingresos_ap_registr_3e283d_idx",
                    ),
                    models.Index(
                        fields=["cedula_titular"], name="ingresos_ap_cedula__c82026_idx"
                    ),
                    models.Index(
                        fields=["telefono_emisor"],
                        name="ingresos_ap_telefon_c60b66_idx",
                    ),
                    models.Index(
                        fields=["referencia"], name="ingresos_ap_referen_f6490d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("referencia", ""), _negated=True),
                        fields=("banco_destino", "referencia", "fecha_pago"),
                        name="aporte_referencia_unica_por_banco_y_fecha",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("monto__gt", 0)),
                        name="aporte_monto_positivo",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MontoConcepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="montos",
                        to="ingresos.conceptoingreso",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="montos_concepto",
                        to="academico.grado",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="montos_concepto",
                        to="core.periodoescolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "monto por concepto",
                "verbose_name_plural": "montos por concepto",
                "ordering": ["periodo", "concepto", "grado__orden"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("concepto", "grado", "periodo"),
                        name="monto_unico_por_concepto_grado_periodo",
                    )
                ],
            },
        ),
    ]
