# Generated by Django 5.2.17 on 2026-09-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aporte",
            name="concepto_libre",
            field=models.CharField(
                blank=True,
                help_text="Nombre escrito en el momento, para un ingreso no planificado que no está en el catálogo (no queda guardado como concepto reutilizable; el ingreso entra siempre al Fondo General).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="historicalaporte",
            name="concepto_libre",
            field=models.CharField(
                blank=True,
                help_text="Nombre escrito en el momento, para un ingreso no planificado que no está en el catálogo (no queda guardado como concepto reutilizable; el ingreso entra siempre al Fondo General).",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="aporte",
            name="concepto",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío si es un ingreso no planificado (usa «concepto libre» en su lugar).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aportes",
                to="ingresos.conceptoingreso",
            ),
        ),
        migrations.AlterField(
            model_name="aporte",
            name="mes_cubierto",
            field=models.DateField(
                blank=True,
                help_text="Día 1 del mes que cubre este aporte. Obligatorio si el concepto es mensual.",
                null=True,
                verbose_name="período que cubre",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaporte",
            name="concepto",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Vacío si es un ingreso no planificado (usa «concepto libre» en su lugar).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ingresos.conceptoingreso",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaporte",
            name="mes_cubierto",
            field=models.DateField(
                blank=True,
                help_text="Día 1 del mes que cubre este aporte. Obligatorio si el concepto es mensual.",
                null=True,
                verbose_name="período que cubre",
            ),
        ),
    ]
