# Generated by Django 5.2.17 on 2026-09-25 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        ("cambio", "0001_initial"),
        ("core", "0004_institucion_permitir_autoaprobacion"),
        ("gastos", "0003_gasto_gastos_gast_fondo_i_4d1b6f_idx"),
        ("ingresos", "0002_aporte_concepto_libre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aporte",
            index=models.Index(
                fields=["fondo", "estado", "fecha_pago"],
                name="ingresos_ap_fondo_i_0f827a_idx",
            ),
        ),
    ]
