# Generated by Django 5.2.17 on 2026-09-22 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif', models.CharField(max_length=20)),
                ('codigo_dea', models.CharField(blank=True, max_length=20, verbose_name='código DEA')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'institución',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 2025-2026', max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'período escolar',
                'verbose_name_plural': 'períodos escolares',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='un_solo_periodo_activo')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('login_fallido', 'Inicio de sesión fallido'), ('verificar', 'Verificación de aporte'), ('anular', 'Anulación'), ('emitir_recibo', 'Emisión de recibo'), ('cargar_tasa', 'Carga de tasa de cambio'), ('cerrar_periodo', 'Cierre de período'), ('reabrir_periodo', 'Reapertura de período')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('objeto_id', models.CharField(blank=True, max_length=64)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'bitácora de auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='core_regist_modelo_a44527_idx'), models.Index(fields=['usuario', 'fecha'], name='core_regist_usuario_ae64b3_idx'), models.Index(fields=['accion', 'fecha'], name='core_regist_accion_f40298_idx')],
            },
        ),
    ]
