# Generated by Django 5.2.17 on 2026-09-22 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('docente', 'Docente'), ('responsable_fondo', 'Responsable de fondo'), ('director', 'Director'), ('auditor', 'Auditor')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('debe_cambiar_clave', models.BooleanField(default=True, help_text='Se pone en True al crear el usuario; se apaga cuando cambia la clave.')),
                ('fondo', models.ForeignKey(blank=True, help_text="Solo para el rol 'Responsable de fondo'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to='gastos.fondo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fondo__isnull', False), ('rol', 'responsable_fondo')), models.Q(models.Q(('rol', 'responsable_fondo'), _negated=True), ('fondo__isnull', True)), _connector='OR'), name='fondo_solo_para_responsable_fondo')],
            },
        ),
    ]
