# Generated by Django 5.2.17 on 2026-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_institucion_codigo_dea"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="permitir_autoaprobacion",
            field=models.BooleanField(
                default=False,
                help_text="G-3 (Fase 5): si está apagado (por defecto), quien registra un gasto no puede aprobarlo — hace falta otro administrador, o confirmar explícitamente la excepción caso por caso. Actívalo solo si la institución tiene un único administrador.",
            ),
        ),
    ]
