# Generated by Django 5.2.17 on 2026-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_institucion_permitir_autoaprobacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("login_fallido", "Inicio de sesión fallido"),
                    ("verificar", "Verificación de aporte"),
                    ("observar", "Observación de aporte"),
                    ("aprobar", "Aprobación de gasto"),
                    ("anular", "Anulación"),
                    ("emitir_recibo", "Emisión de recibo"),
                    ("cargar_tasa", "Carga de tasa de cambio"),
                    ("editar_tasa", "Corrección de tasa de cambio"),
                    ("activar_periodo", "Activación de período"),
                    ("cerrar_periodo", "Cierre de período"),
                    ("reabrir_periodo", "Reapertura de período"),
                ],
                max_length=20,
            ),
        ),
    ]
