# Generated by Django 5.2.17 on 2026-09-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_registroauditoria_accion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("login_fallido", "Inicio de sesión fallido"),
                    ("verificar", "Verificación de aporte"),
                    ("observar", "Observación de aporte"),
                    ("aprobar", "Aprobación de gasto"),
                    ("anular", "Anulación"),
                    ("emitir_recibo", "Emisión de recibo"),
                    ("cargar_tasa", "Carga de tasa de cambio"),
                    ("editar_tasa", "Corrección de tasa de cambio"),
                    ("activar_periodo", "Activación de período"),
                    ("cerrar_periodo", "Cierre de período"),
                    ("reabrir_periodo", "Reapertura de período"),
                    ("crear_usuario", "Creación de usuario"),
                    ("editar_usuario", "Edición de usuario"),
                    ("restablecer_clave", "Restablecimiento de contraseña"),
                    ("activar_usuario", "Activación de usuario"),
                    ("desactivar_usuario", "Desactivación de usuario"),
                    ("crear_fondo", "Creación de fondo"),
                    ("ajustar_saldo_fondo", "Ajuste de saldo inicial de fondo"),
                    ("transferir_fondo", "Transferencia entre fondos"),
                ],
                max_length=20,
            ),
        ),
    ]
