# Generated by Django 5.2.17 on 2026-09-22 23:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTasaCambio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, help_text='Bs. por 1 USD.', max_digits=18)),
                ('fuente', models.CharField(choices=[('bcv', 'BCV'), ('paralelo', 'Paralelo'), ('consejo', 'Consejo'), ('manual', 'Manual')], max_length=10)),
                ('creada_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tasa de cambio',
                'verbose_name_plural': 'historical tasas de cambio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, help_text='Bs. por 1 USD.', max_digits=18)),
                ('fuente', models.CharField(choices=[('bcv', 'BCV'), ('paralelo', 'Paralelo'), ('consejo', 'Consejo'), ('manual', 'Manual')], max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cargada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_cargadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tasa de cambio',
                'verbose_name_plural': 'tasas de cambio',
                'ordering': ['-fecha', 'fuente'],
                'indexes': [models.Index(fields=['fuente', '-fecha'], name='cambio_tasa_fuente_057269_idx')],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'fuente'), name='tasa_unica_por_fecha_y_fuente'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='tasa_valor_positivo')],
            },
        ),
    ]
