# Generated by Django 5.2.17 on 2026-09-25 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        ("ingresos", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SerieRecibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefijo",
                    models.CharField(help_text='Ej: "2026-2027".', max_length=20),
                ),
                ("ultimo_numero", models.PositiveIntegerField(default=0)),
                (
                    "periodo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serie_recibo",
                        to="core.periodoescolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "serie de recibos",
                "verbose_name_plural": "series de recibos",
            },
        ),
        migrations.CreateModel(
            name="Recibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("numero_texto", models.CharField(max_length=40, unique=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_emision", models.DateTimeField()),
                ("entregado_por_texto", models.CharField(blank=True, max_length=150)),
                (
                    "estudiante_texto",
                    models.CharField(
                        blank=True,
                        help_text="Vacío para ingresos sin estudiante (D-19).",
                        max_length=150,
                    ),
                ),
                ("seccion_texto", models.CharField(blank=True, max_length=100)),
                ("concepto_texto", models.CharField(blank=True, max_length=150)),
                ("docente_texto", models.CharField(blank=True, max_length=150)),
                ("anulado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recibos_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aporte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibo",
                        to="ingresos.aporte",
                    ),
                ),
                (
                    "emitido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos_emitidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to="recibos.serierecibo",
                    ),
                ),
            ],
            options={
                "verbose_name": "recibo",
                "verbose_name_plural": "recibos",
                "ordering": ["-numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("serie", "numero"), name="recibo_numero_unico_por_serie"
                    )
                ],
            },
        ),
    ]
