# Generated by Django 5.2.17 on 2026-09-22 20:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_escolar', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='academico_e_apellid_799ea8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cedula_escolar__isnull', False)), fields=('cedula_escolar',), name='cedula_escolar_unica_si_existe')],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 5to grado', max_length=50)),
                ('nivel', models.CharField(choices=[('inicial', 'Inicial'), ('primaria', 'Primaria'), ('media', 'Media')], max_length=10)),
                ('orden', models.PositiveSmallIntegerField(help_text='Define el orden de promoción: el siguiente grado es el de orden inmediato superior.')),
            ],
            options={
                'verbose_name': 'grado',
                'verbose_name_plural': 'grados',
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'nivel'), name='grado_unico_por_nivel')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstudiante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cedula_escolar', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estudiante',
                'verbose_name_plural': 'historical estudiantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRepresentante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical representante',
                'verbose_name_plural': 'historical representantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'representante',
                'verbose_name_plural': 'representantes',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='academico_r_apellid_810401_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cedula__isnull', False)), fields=('cedula',), name='cedula_representante_unica_si_existe')],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: A, B, U', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('docente_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='academico.grado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='core.periodoescolar')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
                'ordering': ['periodo', 'grado__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('egresado', 'Egresado')], default='activo', max_length=10)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.estudiante')),
                ('periodo', models.ForeignKey(help_text='Denormalizado desde seccion.periodo, para filtrar sin JOIN.', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='core.periodoescolar')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.seccion')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'ordering': ['-periodo__fecha_inicio', 'seccion', 'estudiante'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInscripcion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('egresado', 'Egresado')], default='activo', max_length=10)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estudiante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academico.estudiante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, db_constraint=False, help_text='Denormalizado desde seccion.periodo, para filtrar sin JOIN.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.periodoescolar')),
                ('seccion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academico.seccion')),
            ],
            options={
                'verbose_name': 'historical inscripción',
                'verbose_name_plural': 'historical inscripciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EstudianteRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('abuelo_a', 'Abuelo/a'), ('tio_a', 'Tío/a'), ('hermano_a', 'Hermano/a'), ('otro', 'Otro')], max_length=10)),
                ('es_principal', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='academico.estudiante')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academico.representante')),
            ],
            options={
                'verbose_name': 'vínculo estudiante-representante',
                'verbose_name_plural': 'vínculos estudiante-representante',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'representante'), name='vinculo_unico'), models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('estudiante',), name='un_solo_principal_por_estudiante')],
            },
        ),
        migrations.AddIndex(
            model_name='seccion',
            index=models.Index(fields=['periodo', 'docente_responsable'], name='academico_s_periodo_7cf709_idx'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.UniqueConstraint(fields=('grado', 'nombre', 'periodo'), name='seccion_unica_por_periodo'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['periodo', 'estado'], name='academico_i_periodo_b7339b_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['seccion', 'estado'], name='academico_i_seccion_eae1c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'periodo'), name='una_inscripcion_por_periodo'),
        ),
    ]
