# Generated by Django 5.2.17 on 2026-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Comedor, Mantenimiento, General', max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('es_general', models.BooleanField(default=False, help_text='Exactamente un fondo debe tener esto en True: el Fondo General.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fondo',
                'verbose_name_plural': 'fondos',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_general', True)), fields=('es_general',), name='un_solo_fondo_general')],
            },
        ),
    ]
