# Generated by Django 5.2.17 on 2026-09-25 12:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cambio", "0001_initial"),
        ("core", "0004_institucion_permitir_autoaprobacion"),
        ("gastos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40, unique=True)),
                ("abreviatura", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "unidad de medida",
                "verbose_name_plural": "unidades de medida",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fondo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = aplica a cualquier fondo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias_gasto",
                        to="gastos.fondo",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría de gasto",
                "verbose_name_plural": "categorías de gasto",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProveedor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("rif", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical proveedor",
                "verbose_name_plural": "historical proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "nombre_normalizado",
                    models.CharField(editable=False, max_length=120, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="gastos.categoriagasto",
                    ),
                ),
                (
                    "unidad_default",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="gastos.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("rif", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("rif", None), _negated=True),
                        fields=("rif",),
                        name="proveedor_rif_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalGasto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "uuid_cliente",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("nota_entrega", "Nota de entrega"),
                            ("recibo", "Recibo"),
                            ("sin_soporte", "Sin soporte"),
                        ],
                        max_length=15,
                    ),
                ),
                ("numero_documento", models.CharField(blank=True, max_length=40)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("aprobado", "Aprobado"),
                            ("anulado", "Anulado"),
                        ],
                        default="registrado",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                ("autoaprobacion_confirmada", models.BooleanField(default=False)),
                ("saldo_negativo_confirmado", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fondo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Denormalizado: se deduce de la fecha al registrar.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.periodoescolar",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cambio.tasacambio",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gasto",
                "verbose_name_plural": "historical gastos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                ("uuid_cliente", models.UUIDField(blank=True, null=True, unique=True)),
                ("fecha", models.DateField()),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("nota_entrega", "Nota de entrega"),
                            ("recibo", "Recibo"),
                            ("sin_soporte", "Sin soporte"),
                        ],
                        max_length=15,
                    ),
                ),
                ("numero_documento", models.CharField(blank=True, max_length=40)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("aprobado", "Aprobado"),
                            ("anulado", "Anulado"),
                        ],
                        default="registrado",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                ("autoaprobacion_confirmada", models.BooleanField(default=False)),
                ("saldo_negativo_confirmado", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        help_text="Denormalizado: se deduce de la fecha al registrar.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="core.periodoescolar",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="cambio.tasacambio",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="gastos.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "gasto",
                "verbose_name_plural": "gastos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDetalleGasto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "subtotal_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "gasto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.gasto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.producto",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical renglón de gasto",
                "verbose_name_plural": "historical renglones de gasto",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DetalleGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "subtotal_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renglones",
                        to="gastos.gasto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renglones_gasto",
                        to="gastos.producto",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renglones_gasto",
                        to="gastos.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "renglón de gasto",
                "verbose_name_plural": "renglones de gasto",
            },
        ),
        migrations.AddConstraint(
            model_name="categoriagasto",
            constraint=models.UniqueConstraint(
                fields=("nombre", "fondo"), name="categoria_unica_por_nombre_y_fondo"
            ),
        ),
        migrations.AddIndex(
            model_name="gasto",
            index=models.Index(
                fields=["fondo", "fecha"], name="gastos_gast_fondo_i_69a3ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gasto",
            index=models.Index(
                fields=["periodo", "estado"], name="gastos_gast_periodo_2474ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gasto",
            index=models.Index(
                fields=["proveedor", "fecha"], name="gastos_gast_proveed_6a4cfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gasto",
            index=models.Index(
                fields=["registrado_por", "estado"],
                name="gastos_gast_registr_faaec3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gasto",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("proveedor__isnull", False),
                    models.Q(("numero_documento", ""), _negated=True),
                ),
                fields=("proveedor", "tipo_documento", "numero_documento"),
                name="gasto_documento_unico_por_proveedor",
            ),
        ),
        migrations.AddIndex(
            model_name="detallegasto",
            index=models.Index(
                fields=["producto"], name="gastos_deta_product_c38ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallegasto",
            index=models.Index(fields=["gasto"], name="gastos_deta_gasto_i_3a11de_idx"),
        ),
        migrations.AddConstraint(
            model_name="detallegasto",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="detallegasto_cantidad_positiva",
            ),
        ),
    ]
