# Generated by Django 5.2.17 on 2026-09-25 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0003_gasto_gastos_gast_fondo_i_4d1b6f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="fondo",
            name="saldo_inicial_usd",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Saldo en dólares con el que arranca el fondo. No se convierte con la tasa: es un monto aparte, igual que en los aportes y gastos.",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="fondo",
            name="saldo_inicial_ves",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Saldo en bolívares con el que arranca el fondo (antes de cualquier aporte o gasto registrado aquí).",
                max_digits=18,
            ),
        ),
    ]
