# Generated by Django 5.2.17 on 2026-09-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0004_fondo_saldo_inicial_usd_fondo_saldo_inicial_ves"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallegasto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo para cuando el producto no está en el catálogo (si hay producto, la categoría se toma de ahí). Opcional: sin ella, el renglón queda «Sin categoría» en los reportes.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="renglones_gasto",
                to="gastos.categoriagasto",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallegasto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Solo para cuando el producto no está en el catálogo (si hay producto, la categoría se toma de ahí). Opcional: sin ella, el renglón queda «Sin categoría» en los reportes.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="gastos.categoriagasto",
            ),
        ),
    ]
