# Generated by Django 5.2.17 on 2026-09-25 21:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0005_detallegasto_categoria_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTransferenciaFondo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "motivo",
                    models.CharField(
                        help_text="Para qué se mueve el dinero, ej: «Reponer caja chica».",
                        max_length=200,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("registrada", "Registrada"), ("anulada", "Anulada")],
                        default="registrada",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, editable=False)),
                ("saldo_negativo_confirmado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fondo_destino",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "fondo_origen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transferencia entre fondos",
                "verbose_name_plural": "historical transferencias entre fondos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TransferenciaFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "motivo",
                    models.CharField(
                        help_text="Para qué se mueve el dinero, ej: «Reponer caja chica».",
                        max_length=200,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("registrada", "Registrada"), ("anulada", "Anulada")],
                        default="registrada",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("saldo_negativo_confirmado", models.BooleanField(default=False)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_anuladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fondo_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_entrada",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "fondo_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_salida",
                        to="gastos.fondo",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transferencia entre fondos",
                "verbose_name_plural": "transferencias entre fondos",
                "ordering": ["-fecha", "-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["fondo_origen", "estado"],
                        name="gastos_tran_fondo_o_9746f4_idx",
                    ),
                    models.Index(
                        fields=["fondo_destino", "estado"],
                        name="gastos_tran_fondo_d_04da5d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("monto__gt", 0)),
                        name="transferenciafondo_monto_positivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fondo_origen", models.F("fondo_destino")), _negated=True
                        ),
                        name="transferenciafondo_fondos_distintos",
                    ),
                ],
            },
        ),
    ]
